### ISSUE TITLE
Use auto closure and inferred type

### ISSUE THREAD

**Issue by AliSoftware** [vincent-pradeilles/locatable#1]
On my phone so not ideal to make the PR myself but you should change to this:

```
static func register<T>(_ type: T.Type = T.self, _ factory: @autoclosure @escaping () -> T) {
```

This would allow the call site to either choose to use the autoclosure feature:

```
Resolver.register( Servicing.self, Service() )
```
Or to use the `= T.self` and inference and be able to write:
```
Resolver.register { Service() as Servicing }
```

**Comment by vincent-pradeilles** [comment]
I forgot to answer that this has been implemented.

Thanks for your input!
